accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('sign-up/', views.sign_up, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

app/urls.py
from django.urls import path, re_path
from .views import article_list, show_detail, create_article, update_article, delete_article
from django.conf.urls.static import static
from django.conf import settings

app_name = "articles"

urlpatterns = [
    path('', article_list, name="article_list"),
    path('create/', create_article , name='create'),
    path('<slug:slug>/', show_detail, name="details"),
    path('update/<int:id>/', update_article, name="update_article"),
    path('delete/<int:id>', delete_article, name="delete_article"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(default='default.png',blank=True)
    author = models.ForeignKey(User, default = None ,on_delete=models.CASCADE)
    def __str__(self):
        return self.title 
    
    def snippet(self):
        return self.body[:150]+ "..."
    
    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"slug": self.slug})

    def get_absolute_url(self):
        return reverse("arty", kwargs={"slug": self.slug})

app/forms.py
from django import forms
from . import models

class Create_article(forms.ModelForm):
    class Meta:
       model = models.Article
       fields = [
           "title", "slug", "body", "photo"
       ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
#UserCreationForm is responsible for the form of creating a now user 
from django.contrib.auth import login as lg 
from django.contrib.auth import logout as lo

def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            lg(request, user)
            return redirect('articles:article_list') 
    else:   
        form = UserCreationForm
    return render(request, "accounts/signup.html", {'form':form})

def login(request):
    if request.method == 'POST':
        login = AuthenticationForm(data=request.POST)
        if login.is_valid():
            user = login.get_user()
            lg(request, user)
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            return redirect('articles:article_list') 
    else:
        login = AuthenticationForm()
    return render(request, 'accounts/login.html', {'login': login})    

def logout(request):
    lo(request)
    return redirect("articles:article_list")    

app/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from . import forms
def article_list(request):
    articles = Article.objects.all().order_by("date")
    return render(request, "app/article_list.html", {'articles':articles})

def show_detail(request, slug):
    article_detail = Article.objects.get(slug=slug)
    a = render(request, "app/detail_view.html", {"article_details":article_detail})
    return a

@login_required(login_url="/accounts/login")
def create_article(request):
    form = forms.Create_article
    if request.method == "POST":
        form = forms.Create_article(request.POST, request.FILES)
        if form.is_valid():
            a = form.save(commit=False)
            a.author = request.user
            a.save()
        return redirect('/')
    
    return render(request, 'app/create.html', {'form':form})

@login_required(login_url="/accounts/login")
def update_article(request, id):
   arty = Article.objects.get(id=id)
   form = forms.Create_article(instance=arty) 
   if request.method == "POST":
        form = forms.Create_article(request.POST, request.FILES,instance=arty )
        if form.is_valid():
            form.save()
            return redirect('/')
   return render(request, 'app/create.html',{'form':form})
    
@login_required(login_url="/accounts/login")
def delete_article(request, id):
   arty = Article.objects.get(id=id)
   if request.method == "POST":
        arty.delete()
        return redirect('/')
   return render(request, 'app/delete.html',{'article':arty})
        

accounts/templates/accounts/login.html

{% extends 'app/navbar.html' %}
{%load static%}
<link rel="stylesheet" href="/static/style.css">
<link rel="stylesheet" href="/static/admin/login.css">
{% block content %}
<div class="container">
<form  id="login_menu" method = "POST" action="{% url 'accounts:login'%}">
    {% csrf_token %}
    {{login.as_p}}
    <br>
    <i><a href="/accounts/sign-up/">Register</a></i>
    {% if request.GET.next %}
    
     <input type='hidden' name='next' value='{{ request.GET.next }}'>   
    {% endif %}
    <br> 
    <br>
    <button class="btn btn-dark" type='submit' value='Login'>Login</button>
</form>
{% endblock content %}
    

accounts/templates/accounts/signup.html

{% extends 'app/navbar.html' %}
{%load static%}
<link rel="stylesheet" href="/static/css/style.css">

{% block content %}
<form id="sign_up_menu" method = "POST" action="/accounts/sign-up/">
    {% csrf_token %}
    {{form}}
    <br>
    <br>
    <button class="btn btn-dark" type='submit' value='Sign up'>Sign up</button>
</form>
</div>
{% endblock content %}
    

app/templates/app/article_list.html
{% extends 'app/navbar.html' %}
{%load static%}
<link rel="stylesheet" href="/static/css/style.css">
{%block content%}

        <p class='header'>Article List</p>
        <div class="container" id="article_list">
            {% for article in articles %}
                <div class="article">
                    <h2><a type="button" class="article_link" href="{%url 'articles:details' slug=article.slug%}">{{ article.title }}</a></h2> 
                    {% if user.is_authenticated and user == article.author %}
                    <i><a href="{%url 'articles:update_article' id=article.id%}">Update</a></i>
                    <i><a href="{%url 'articles:delete_article' id=article.id%}">Delete</a></i> 
                    {% endif %}
                    <p class= "snippet">{{ article.snippet }}</p>
                    <p class="author">Created By {{article.author}} </p>
                    <i>{{ article.date }}</i>
                    <hr>
                </div>    
            {% endfor %}
        </div>
{% endblock content%}

app/templates/app/create.html

{% extends 'app/navbar.html' %}
{%load static%}
<link rel="stylesheet" href="/static/css/style.css">

{% block content %}
    <div>
        <p class="header">Create New Article</p>
        <form id="article_create" method='POST' action="" enctype="multipart/form-data">
            <div class="container_create">
            {% csrf_token %}
            {{form}}
            </div>
        <br>
        <button class="btn btn-dark" type='submit' value='Create'>Create</button>    
        </form>
    </div>
{% endblock content %}
    

app/templates/app/delete.html

{% extends 'app/navbar.html' %}
{%load static%}
<link rel="stylesheet" href="/static/css/style.css">

{% block content %}
    <div>
        <p class="header">Delete</p>
        <form id="article_delete" method='POST' action="{%url 'articles:delete_article' id=article.id%}">
            {% csrf_token %}
        <p class="article_body">Do you want to delete <b>'{{article}}'</b>?</p>
        <br>
        <br>
        
        
        <button class="btn btn-dark" type='submit'> Delete</button>   
        <a  class="btn btn-outline-dark" href="/">Cancel</a> 
    </form>

          
    </div>
{% endblock content %}
    

app/templates/app/detail_view.html

{% extends 'app/navbar.html' %}
{%load static%}
<link rel="stylesheet" href="/static/style.css">
{%block content%}
<div id="article_detail">
    <p class="article_title">{{article_details.title}}</p>

    <img class="img-fluid mx-auto" src = "{{article_details.photo.url}}" />
    <p class="article_body">{{article_details.body}}</p>
    <hr>
    <i>{{article_details.date}}</i>
    <p class="author">Created By {{article_details.author}}</p>
       
</div>
{%endblock content%}

app/templates/app/navbar.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/style.css">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>Document</title>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="/"><b>Articles</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="btn btn-dark" style="margin-right:8px;"aria-current="page" role="button" href="/create/">Create New Article</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="btn btn-outline-dark" role="button"  href="/accounts/logout/">Logout</a>
              </li>
              {%else%}
              <li class="nav-item">
                <a class="btn btn-outline-dark" role="button"  href="/accounts/login/">Login</a>
              </li>
              {%endif%}

            </form>
          </div>
        </div>
      </nav>
    </head>
<body>
    
    {% block content %}
        
    {% endblock content %}
        
</body>
</html>